---
- name: Provision Linux servers
  hosts: linux_servers
  gather_facts: true
  roles:
    - role: packages
      vars:
        packages_present: "{{ linux_packages_present + (extra_packages_present | default([])) }}"
        packages_absent: "{{ linux_packages_absent }}"

    - role: users
      vars:
        users: "{{ linux_users }}"
        users_absent: "{{ linux_users_absent }}"

- name: Provision Docker hosts
  hosts: docker_hosts
  gather_facts: true
  roles:
    - role: docker
  tags: 
    - install_docker

- name: Provision Syslog storage
  hosts: syslog_storage
  gather_facts: true
  roles:
    - role: syslog_permissions
      vars:
        syslog_users: "{{ syslog_viewer_users }}"
        syslog_groups: "{{ syslog_groups_present }}"