---
- name: Install linux packages
  hosts: linux_servers
  gather_facts: true
  tags:
    - packages
  roles:
    - role: packages
      vars:
        packages_present: "{{ linux_packages_present + (extra_packages_present | default([])) }}"
        packages_absent: "{{ linux_packages_absent }}"

- name: Create linux users
  hosts: linux_servers
  gather_facts: true
  tags:
    - users
  roles:
    - role: users
      vars:
        users: "{{ linux_users }}"
        users_absent: "{{ linux_users_absent }}"

- name: Provision Docker hosts
  hosts: docker_hosts
  gather_facts: true
  roles:
    - role: docker
  tags: 
    - docker

- name: Configure keepalived on syslog caches
  hosts: syslog_caches
  gather_facts: true
  tags:
    - keepalived
  roles:
    - role: keepalived


- name: Configure syslog servers
  hosts:
    - syslog_caches
    - syslog_storage
  gather_facts: true
  tags:
    - syslog
  roles:
    - role: syslog
  vars:
    syslog_users: "{{ syslog_viewer_users }}"
    syslog_groups: "{{ syslog_groups_present }}"

