---
all:
  children:
    linux_servers:
      children:
        debian_servers:
          children:
            syslog_caches:
              hosts:
                syslog-cache-01:
                  ansible_host: 192.168.4.31
                syslog-cache-02:
                  ansible_host: 192.168.4.32
            syslog_storage:
              hosts:
                syslog-storage:
                  ansible_host: 192.168.4.33
            docker_hosts:
              hosts:
                docker-host-01:
                  ansible_host: 192.168.4.200


      vars:
        ansible_python_interpreter: /usr/bin/python3
