---
all:
  hosts:
    syslog-storage:
      ansible_host: 192.168.4.33
    syslog-cache-01:
      ansible_host: 192.168.4.31
    syslog-cache-02:
      ansible_host: 192.168.4.32
    docker-host-01:
      ansible_host: 192.168.4.200
  children:
    linux_servers:
      children:
        debian_servers:
          children:
            syslog_caches:
              hosts:
                syslog-cache-01:
                syslog-cache-02:
            syslog_storage:
              hosts:
                syslog-storage:
            docker_hosts:
              hosts:
                docker-host-01:


      vars:
        ansible_python_interpreter: /usr/bin/python3
