# Managed by Ansible

# Standard system logs (Low volume)
/var/log/remote/bluecat/dns.log
/var/log/remote/bluecat/audit.log
/var/log/remote/bluecat/system.log
/var/log/remote/misc/*/*.log {
    daily
    rotate 90
    compress
    delaycompress
    missingok
    notifempty
    sharedscripts
    create 0640 root logviewer
    postrotate
        /usr/lib/rsyslog/rsyslog-rotate
    endscript
}

# DHCP logs (High volume)
/var/log/remote/bluecat/dhcp.log {
    daily
    rotate 730
    compress
    delaycompress
    missingok
    notifempty
    sharedscripts
    create 0640 root logviewer
    postrotate
        /usr/lib/rsyslog/rsyslog-rotate
    endscript
}
