# managed by Ansible
# provides RELP syslog reception
module(load="imrelp")
input(type="imrelp" port="2514")

# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# provides TCP syslog reception
module(load="imtcp")
input(type="imtcp" port="514")


if ($hostname contains "ns01") or ($hostname contains "ns02") then {

	if $syslogtag contains "named"  then {
		action(type="omfile" file="/var/log/remote/bluecat/dns.log" {{ omfile_options }})
	} else if $syslogtag contains "dhcp" then {
		action(type="omfile" file="/var/log/remote/bluecat/dhcpd.log" {{ omfile_options }})
	} else if $syslogfacility-text == "local6" then {
		action(type="omfile" file="/var/log/remote/bluecat/audit.log" {{ omfile_options }})
	} else {
		action(type="omfile" file="/var/log/remote/bluecat/system.log" {{ omfile_options }} )
	}
    stop

}


template(name="HostnameFile" type="string" string="/var/log/remote/misc/%HOSTNAME%/%programname%.log")

*.* action(type="omfile" dynaFile="HostnameFile" {{ omfile_options }})
