# managed by Ansible
# provides RELP syslog reception
module(load="imrelp")
input(type="imrelp" port="2514")

# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# provides TCP syslog reception
module(load="imtcp")
input(type="imtcp" port="514")

template(name="HostnameFile" type="string" string="/var/log/remote/%HOSTNAME%/messages.log")

*.* action(type="omfile" dynaFile="HostnameFile")
