---
- name: Provision groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: "{{ item.state }}"
  loop: "{{ syslog_groups }}"
  when: syslog_groups | length > 0

- name: Assign users to logviewer group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "logviewer"
    append: true
  loop: "{{ syslog_users }}"
  when: syslog_users | length > 0

- name: Calculate rsyslog template name
  ansible.builtin.set_fact:
      rsyslog_template_name: >-
        {{ group_to_template[group_names | intersect(group_to_template.keys()) | first | default('default')] }}

- name: Configure rsyslog
  ansible.builtin.template:
    src: "{{ rsyslog_template_name }}"
    dest: "/etc/rsyslog.d/remote.conf"
  notify: Restart syslog

- name: Configure log rotation
  ansible.builtin.template:
    src: "logrotate.conf"
    dest: "/etc/logrotate.d/remote"
  when: inventory_hostname in groups['syslog_storage']
