---
- name: Ensure absent users are removed
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: absent
    remove: true
  loop: "{{ users_absent }}"

- name: Ensure users are present
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | default([]) }}"
    append: true
    state: "{{ item.state | default('present') }}"
    password_lock: "{{ item.password_lock | default(false) }}"
  loop: "{{ users }}"

- name: Ensure SSH authorized keys are configured
  ansible.posix.authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: present
  loop: "{{ users | subelements('ssh_authorized_keys', skip_missing=True) }}"
