#SPDX-License-Identifier: MIT-0
---

- name: Install rsyslog health check
  ansible.builtin.template:
    src: check_rsyslog.sh
    dest: /etc/keepalived/check_rsyslog.sh
    owner: root
    group: root
    mode: '0755'

# tasks file for vrrp
- name: Configure keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: Restart keepalived

