---
- name: Install Docker repo prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
    state: present
    update_cache: true

- name: Add Docker APT repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "{{ docker_repo_base_url }}/{{ ansible_facts['distribution'] | lower }}"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    architectures: "{{ docker_arch_map[ansible_facts['architecture']] | default(ansible_facts['architecture']) }}"
    signed_by: "{{ docker_repo_base_url }}/{{ ansible_facts['distribution'] | lower }}/gpg"
    state: present
