---
# Users to manage on syslog servers
linux_users:
  - name: dmcnish
    comment: "Doug McNish"
    shell: /bin/bash
    uid: 20001
    password: "{{ lookup('file', 'passwords/dmcnish.pass') }}"
    groups:
      - sudo
    state: present
    ssh_authorized_keys:
      - "{{ lookup('file', 'ssh_keys/dmcnish.pub') }}"
    update_password: always
    password_lock: false

  # - name: svcaccount
  #   uid: 20002
  #   comment: "Service Account"
  #   shell: /sbin/nologin
  #   groups: []
  #   state: present
  #   password_lock: true


# Users to remove
linux_users_absent:
  - name: olduser
    state: absent

