---
# Users to manage on syslog servers
linux_users:
  - name: dmcnish
    comment: "Doug McNish"
    shell: /bin/bash
    uid: 20001
    password: "{{ lookup('file', 'passwords/dmcnish.pass') }}"
    groups:
      - sudo
    state: present
    ssh_authorized_keys:
      - "{{ lookup('file', 'ssh_keys/dmcnish.pub') }}"
    update_password: always
    password_lock: false
  - name: jkring
    comment: "Josh Kring"
    shell: /bin/bash
    uid: 20002
    password: "{{ lookup('file', 'passwords/jkring.pass') }}"
    groups:
      - sudo
    state: present
    ssh_authorized_keys:
      - "{{ lookup('file', 'ssh_keys/jkring.pub') }}"
    update_password: always
    password_lock: false
  - name: pwilson
    comment: "Patrick Wilson"
    shell: /bin/bash
    uid: 20003
    password: "{{ lookup('file', 'passwords/pwilson.pass') }}"
    groups:
      - sudo
    state: present
    ssh_authorized_keys:
      - "{{ lookup('file', 'ssh_keys/pwilson.pub') }}"
    update_password: always
    password_lock: false
  - name: jmays
    comment: "Jessie Mays"
    shell: /bin/bash
    uid: 20004
    password: "{{ lookup('file', 'passwords/jmays.pass') }}"
    groups:
      - sudo
    state: present
    ssh_authorized_keys:
      - "{{ lookup('file', 'ssh_keys/jmays.pub') }}"
    update_password: always
    password_lock: false
  - name: fcamp
    comment: "Franklin Camp"
    shell: /bin/bash
    uid: 20005
    password: "{{ lookup('file', 'passwords/fcamp.pass') }}"
    groups:
      - sudo
    state: present
    ssh_authorized_keys:
      - "{{ lookup('file', 'ssh_keys/fcamp.pub') }}"
    update_password: always
    password_lock: false

  # - name: svcaccount
  #   uid: 20002
  #   comment: "Service Account"
  #   shell: /sbin/nologin
  #   groups: []
  #   state: present
  #   password_lock: true


# Users to remove
linux_users_absent:
  - name: olduser
    state: absent

